
CAT_LEVEL_FILES = {
	"BackStab": [
		"audio_CaptureTheFlag.cat",
		"audio_common.cat",
		"audio_conquest.cat",
		"textures.cat",
		"texturesCaptureTheFlag.cat",
		"texturesconquest.cat",
		"audiolocale/ARMY/audio_CaptureTheFlag.cat",
		"audiolocale/ARMY/audio_conquest.cat",
		"audiolocale/FRENCH/audio_CaptureTheFlag.cat",
		"audiolocale/FRENCH/audio_conquest.cat",
		"audiolocale/GERMAN/audio_CaptureTheFlag.cat",
		"audiolocale/GERMAN/audio_conquest.cat",
		"audiolocale/ITALIAN/audio_CaptureTheFlag.cat",
		"audiolocale/ITALIAN/audio_conquest.cat",
		"audiolocale/JAPANESE/audio_CaptureTheFlag.cat",
		"audiolocale/JAPANESE/audio_conquest.cat",
		"audiolocale/SPANISH/audio_CaptureTheFlag.cat",
		"audiolocale/SPANISH/audio_conquest.cat",
		"audiolocale/UK/audio_CaptureTheFlag.cat",
		"audiolocale/UK/audio_conquest.cat",
		"audiolocale/US/audio_CaptureTheFlag.cat",
		"audiolocale/US/audio_conquest.cat",
	],
	"BridgeTooFar": [
		"audio_capturetheflag.cat",
		"audio_common.cat",
		"audio_conquest.cat",
		"textures.cat",
		"texturescapturetheflag.cat",
		"texturesconquest.cat",
		"audiolocale/ARMY/audio_capturetheflag.cat",
		"audiolocale/ARMY/audio_conquest.cat",
		"audiolocale/FRENCH/audio_capturetheflag.cat",
		"audiolocale/FRENCH/audio_conquest.cat",
		"audiolocale/GERMAN/audio_capturetheflag.cat",
		"audiolocale/GERMAN/audio_conquest.cat",
		"audiolocale/ITALIAN/audio_capturetheflag.cat",
		"audiolocale/ITALIAN/audio_conquest.cat",
		"audiolocale/JAPANESE/audio_capturetheflag.cat",
		"audiolocale/JAPANESE/audio_conquest.cat",
		"audiolocale/SPANISH/audio_capturetheflag.cat",
		"audiolocale/SPANISH/audio_conquest.cat",
		"audiolocale/UK/audio_capturetheflag.cat",
		"audiolocale/UK/audio_conquest.cat",
		"audiolocale/US/audio_capturetheflag.cat",
		"audiolocale/US/audio_conquest.cat",
	],
	"ColdFront": [
		"audio_CaptureTheFlag.cat",
		"audio_common.cat",
		"audio_Conquest.cat",
		"textures.cat",
		"texturesCaptureTheFlag.cat",
		"texturesConquest.cat",
		"audiolocale/ARMY/audio_CaptureTheFlag.cat",
		"audiolocale/ARMY/audio_Conquest.cat",
		"audiolocale/FRENCH/audio_CaptureTheFlag.cat",
		"audiolocale/FRENCH/audio_Conquest.cat",
		"audiolocale/GERMAN/audio_CaptureTheFlag.cat",
		"audiolocale/GERMAN/audio_Conquest.cat",
		"audiolocale/ITALIAN/audio_CaptureTheFlag.cat",
		"audiolocale/ITALIAN/audio_Conquest.cat",
		"audiolocale/JAPANESE/audio_CaptureTheFlag.cat",
		"audiolocale/JAPANESE/audio_Conquest.cat",
		"audiolocale/SPANISH/audio_CaptureTheFlag.cat",
		"audiolocale/SPANISH/audio_Conquest.cat",
		"audiolocale/UK/audio_CaptureTheFlag.cat",
		"audiolocale/UK/audio_Conquest.cat",
		"audiolocale/US/audio_CaptureTheFlag.cat",
		"audiolocale/US/audio_Conquest.cat",
	],
	"Dammage": [
		"audio_CaptureTheFlag.cat",
		"audio_common.cat",
		"audio_Conquest.cat",
		"textures.cat",
		"texturesCaptureTheFlag.cat",
		"texturesConquest.cat",
		"audiolocale/ARMY/audio_CaptureTheFlag.cat",
		"audiolocale/ARMY/audio_Conquest.cat",
		"audiolocale/FRENCH/audio_CaptureTheFlag.cat",
		"audiolocale/FRENCH/audio_Conquest.cat",
		"audiolocale/GERMAN/audio_CaptureTheFlag.cat",
		"audiolocale/GERMAN/audio_Conquest.cat",
		"audiolocale/ITALIAN/audio_CaptureTheFlag.cat",
		"audiolocale/ITALIAN/audio_Conquest.cat",
		"audiolocale/JAPANESE/audio_CaptureTheFlag.cat",
		"audiolocale/JAPANESE/audio_Conquest.cat",
		"audiolocale/SPANISH/audio_CaptureTheFlag.cat",
		"audiolocale/SPANISH/audio_Conquest.cat",
		"audiolocale/UK/audio_CaptureTheFlag.cat",
		"audiolocale/UK/audio_Conquest.cat",
		"audiolocale/US/audio_CaptureTheFlag.cat",
		"audiolocale/US/audio_Conquest.cat",
	],
	"DeadlyPass": [
		"audio_CaptureTheFlag.cat",
		"audio_common.cat",
		"audio_conquest.cat",
		"textures.cat",
		"texturesCaptureTheFlag.cat",
		"texturesconquest.cat",
		"audiolocale/ARMY/audio_CaptureTheFlag.cat",
		"audiolocale/ARMY/audio_conquest.cat",
		"audiolocale/FRENCH/audio_CaptureTheFlag.cat",
		"audiolocale/FRENCH/audio_conquest.cat",
		"audiolocale/GERMAN/audio_CaptureTheFlag.cat",
		"audiolocale/GERMAN/audio_conquest.cat",
		"audiolocale/ITALIAN/audio_CaptureTheFlag.cat",
		"audiolocale/ITALIAN/audio_conquest.cat",
		"audiolocale/JAPANESE/audio_CaptureTheFlag.cat",
		"audiolocale/JAPANESE/audio_conquest.cat",
		"audiolocale/SPANISH/audio_CaptureTheFlag.cat",
		"audiolocale/SPANISH/audio_conquest.cat",
		"audiolocale/UK/audio_CaptureTheFlag.cat",
		"audiolocale/UK/audio_conquest.cat",
		"audiolocale/US/audio_CaptureTheFlag.cat",
		"audiolocale/US/audio_conquest.cat",
	],
	"HarborEdge": [
		"audio_CaptureTheFlag.cat",
		"audio_common.cat",
		"audio_Conquest.cat",
		"textures.cat",
		"texturesCaptureTheFlag.cat",
		"texturesConquest.cat",
		"audiolocale/ARMY/audio_CaptureTheFlag.cat",
		"audiolocale/ARMY/audio_Conquest.cat",
		"audiolocale/FRENCH/audio_CaptureTheFlag.cat",
		"audiolocale/FRENCH/audio_Conquest.cat",
		"audiolocale/GERMAN/audio_CaptureTheFlag.cat",
		"audiolocale/GERMAN/audio_Conquest.cat",
		"audiolocale/ITALIAN/audio_CaptureTheFlag.cat",
		"audiolocale/ITALIAN/audio_Conquest.cat",
		"audiolocale/JAPANESE/audio_CaptureTheFlag.cat",
		"audiolocale/JAPANESE/audio_Conquest.cat",
		"audiolocale/SPANISH/audio_CaptureTheFlag.cat",
		"audiolocale/SPANISH/audio_Conquest.cat",
		"audiolocale/UK/audio_CaptureTheFlag.cat",
		"audiolocale/UK/audio_Conquest.cat",
		"audiolocale/US/audio_CaptureTheFlag.cat",
		"audiolocale/US/audio_Conquest.cat",
	],
	"Honor": [
		"audio_CaptureTheFlag.cat",
		"audio_common.cat",
		"audio_conquest.cat",
		"textures.cat",
		"texturesCaptureTheFlag.cat",
		"texturesconquest.cat",
		"audiolocale/ARMY/audio_CaptureTheFlag.cat",
		"audiolocale/ARMY/audio_conquest.cat",
		"audiolocale/FRENCH/audio_CaptureTheFlag.cat",
		"audiolocale/FRENCH/audio_conquest.cat",
		"audiolocale/GERMAN/audio_CaptureTheFlag.cat",
		"audiolocale/GERMAN/audio_conquest.cat",
		"audiolocale/ITALIAN/audio_CaptureTheFlag.cat",
		"audiolocale/ITALIAN/audio_conquest.cat",
		"audiolocale/JAPANESE/audio_CaptureTheFlag.cat",
		"audiolocale/JAPANESE/audio_conquest.cat",
		"audiolocale/SPANISH/audio_CaptureTheFlag.cat",
		"audiolocale/SPANISH/audio_conquest.cat",
		"audiolocale/UK/audio_CaptureTheFlag.cat",
		"audiolocale/UK/audio_conquest.cat",
		"audiolocale/US/audio_CaptureTheFlag.cat",
		"audiolocale/US/audio_conquest.cat",
	],
	"LittleBigEye": [
		"audio_CaptureTheFlag.cat",
		"audio_common.cat",
		"audio_conquest.cat",
		"textures.cat",
		"texturesCaptureTheFlag.cat",
		"texturesconquest.cat",
		"audiolocale/ARMY/audio_CaptureTheFlag.cat",
		"audiolocale/ARMY/audio_conquest.cat",
		"audiolocale/FRENCH/audio_CaptureTheFlag.cat",
		"audiolocale/FRENCH/audio_conquest.cat",
		"audiolocale/GERMAN/audio_CaptureTheFlag.cat",
		"audiolocale/GERMAN/audio_conquest.cat",
		"audiolocale/ITALIAN/audio_CaptureTheFlag.cat",
		"audiolocale/ITALIAN/audio_conquest.cat",
		"audiolocale/JAPANESE/audio_CaptureTheFlag.cat",
		"audiolocale/JAPANESE/audio_conquest.cat",
		"audiolocale/SPANISH/audio_CaptureTheFlag.cat",
		"audiolocale/SPANISH/audio_conquest.cat",
		"audiolocale/UK/audio_CaptureTheFlag.cat",
		"audiolocale/UK/audio_conquest.cat",
		"audiolocale/US/audio_CaptureTheFlag.cat",
		"audiolocale/US/audio_conquest.cat",
	],
	"MissileCrisis": [
		"audio_CaptureTheFlag.cat",
		"audio_common.cat",
		"audio_conquest.cat",
		"textures.cat",
		"texturesCaptureTheFlag.cat",
		"texturesconquest.cat",
		"audiolocale/ARMY/audio_CaptureTheFlag.cat",
		"audiolocale/ARMY/audio_conquest.cat",
		"audiolocale/FRENCH/audio_CaptureTheFlag.cat",
		"audiolocale/FRENCH/audio_conquest.cat",
		"audiolocale/GERMAN/audio_CaptureTheFlag.cat",
		"audiolocale/GERMAN/audio_conquest.cat",
		"audiolocale/ITALIAN/audio_CaptureTheFlag.cat",
		"audiolocale/ITALIAN/audio_conquest.cat",
		"audiolocale/JAPANESE/audio_CaptureTheFlag.cat",
		"audiolocale/JAPANESE/audio_conquest.cat",
		"audiolocale/SPANISH/audio_CaptureTheFlag.cat",
		"audiolocale/SPANISH/audio_conquest.cat",
		"audiolocale/UK/audio_CaptureTheFlag.cat",
		"audiolocale/UK/audio_conquest.cat",
		"audiolocale/US/audio_CaptureTheFlag.cat",
		"audiolocale/US/audio_conquest.cat",
	],
	"RussianBorder": [
		"audio_CaptureTheFlag.cat",
		"audio_common.cat",
		"audio_conquest.cat",
		"textures.cat",
		"texturesCaptureTheFlag.cat",
		"texturesconquest.cat",
		"audiolocale/ARMY/audio_CaptureTheFlag.cat",
		"audiolocale/ARMY/audio_conquest.cat",
		"audiolocale/FRENCH/audio_CaptureTheFlag.cat",
		"audiolocale/FRENCH/audio_conquest.cat",
		"audiolocale/GERMAN/audio_CaptureTheFlag.cat",
		"audiolocale/GERMAN/audio_conquest.cat",
		"audiolocale/ITALIAN/audio_CaptureTheFlag.cat",
		"audiolocale/ITALIAN/audio_conquest.cat",
		"audiolocale/JAPANESE/audio_CaptureTheFlag.cat",
		"audiolocale/JAPANESE/audio_conquest.cat",
		"audiolocale/SPANISH/audio_CaptureTheFlag.cat",
		"audiolocale/SPANISH/audio_conquest.cat",
		"audiolocale/UK/audio_CaptureTheFlag.cat",
		"audiolocale/UK/audio_conquest.cat",
		"audiolocale/US/audio_CaptureTheFlag.cat",
		"audiolocale/US/audio_conquest.cat",
	],
	"SpecialOp": [
		"audio_CaptureTheFlag.cat",
		"audio_common.cat",
		"audio_conquest.cat",
		"textures.cat",
		"texturesCaptureTheFlag.cat",
		"texturesconquest.cat",
		"audiolocale/ARMY/audio_CaptureTheFlag.cat",
		"audiolocale/ARMY/audio_conquest.cat",
		"audiolocale/FRENCH/audio_CaptureTheFlag.cat",
		"audiolocale/FRENCH/audio_conquest.cat",
		"audiolocale/GERMAN/audio_CaptureTheFlag.cat",
		"audiolocale/GERMAN/audio_conquest.cat",
		"audiolocale/ITALIAN/audio_CaptureTheFlag.cat",
		"audiolocale/ITALIAN/audio_conquest.cat",
		"audiolocale/JAPANESE/audio_CaptureTheFlag.cat",
		"audiolocale/JAPANESE/audio_conquest.cat",
		"audiolocale/SPANISH/audio_CaptureTheFlag.cat",
		"audiolocale/SPANISH/audio_conquest.cat",
		"audiolocale/UK/audio_CaptureTheFlag.cat",
		"audiolocale/UK/audio_conquest.cat",
		"audiolocale/US/audio_CaptureTheFlag.cat",
		"audiolocale/US/audio_conquest.cat",
	],
	"TheBlackGold": [
		"audio_CaptureTheFlag.cat",
		"audio_common.cat",
		"audio_conquest.cat",
		"textures.cat",
		"texturesCaptureTheFlag.cat",
		"texturesconquest.cat",
		"audiolocale/ARMY/audio_CaptureTheFlag.cat",
		"audiolocale/ARMY/audio_conquest.cat",
		"audiolocale/FRENCH/audio_CaptureTheFlag.cat",
		"audiolocale/FRENCH/audio_conquest.cat",
		"audiolocale/GERMAN/audio_CaptureTheFlag.cat",
		"audiolocale/GERMAN/audio_conquest.cat",
		"audiolocale/ITALIAN/audio_CaptureTheFlag.cat",
		"audiolocale/ITALIAN/audio_conquest.cat",
		"audiolocale/JAPANESE/audio_CaptureTheFlag.cat",
		"audiolocale/JAPANESE/audio_conquest.cat",
		"audiolocale/SPANISH/audio_CaptureTheFlag.cat",
		"audiolocale/SPANISH/audio_conquest.cat",
		"audiolocale/UK/audio_CaptureTheFlag.cat",
		"audiolocale/UK/audio_conquest.cat",
		"audiolocale/US/audio_CaptureTheFlag.cat",
		"audiolocale/US/audio_conquest.cat",
	],
	"TheNest": [
		"audio_CaptureTheFlag.cat",
		"audio_common.cat",
		"audio_Conquest.cat",
		"textures.cat",
		"texturesCaptureTheFlag.cat",
		"texturesConquest.cat",
		"audiolocale/ARMY/audio_CaptureTheFlag.cat",
		"audiolocale/ARMY/audio_Conquest.cat",
		"audiolocale/FRENCH/audio_CaptureTheFlag.cat",
		"audiolocale/FRENCH/audio_Conquest.cat",
		"audiolocale/GERMAN/audio_CaptureTheFlag.cat",
		"audiolocale/GERMAN/audio_Conquest.cat",
		"audiolocale/ITALIAN/audio_CaptureTheFlag.cat",
		"audiolocale/ITALIAN/audio_Conquest.cat",
		"audiolocale/JAPANESE/audio_CaptureTheFlag.cat",
		"audiolocale/JAPANESE/audio_Conquest.cat",
		"audiolocale/SPANISH/audio_CaptureTheFlag.cat",
		"audiolocale/SPANISH/audio_Conquest.cat",
		"audiolocale/UK/audio_CaptureTheFlag.cat",
		"audiolocale/UK/audio_Conquest.cat",
		"audiolocale/US/audio_CaptureTheFlag.cat",
		"audiolocale/US/audio_Conquest.cat",
	],
}

CAT_LEVEL_FILES_ALPHA = {
    "BackStab": [
        "audio_CaptureTheFlag.cat",
        "audio_common.cat",
        "audio_conquest.cat",
        "textures.cat",
        "texturesCaptureTheFlag.cat",
        "texturesconquest.cat",

    ],
    "BridgeTooFar": [
        "audio_capturetheflag.cat",
        "audio_common.cat",
        "audio_conquest.cat",
        "textures.cat",
        "texturescapturetheflag.cat",
        "texturesconquest.cat",

    ],
    "ColdFront": [
        "audio_CaptureTheFlag.cat",
        "audio_common.cat",
        "audio_Conquest.cat",
        "textures.cat",
        "texturesCaptureTheFlag.cat",
        "texturesConquest.cat",

    ],
    "Dammage": [
        "audio_CaptureTheFlag.cat",
        "audio_common.cat",
        "audio_Conquest.cat",
        "textures.cat",
        "texturesCaptureTheFlag.cat",
        "texturesConquest.cat",

    ],
    "DeadlyPass": [
        "audio_CaptureTheFlag.cat",
        "audio_common.cat",
        "audio_conquest.cat",
        "textures.cat",
        "texturesCaptureTheFlag.cat",
        "texturesconquest.cat",

    ],
    "HarborEdge": [
        "audio_CaptureTheFlag.cat",
        "audio_common.cat",
        "audio_Conquest.cat",
        "textures.cat",
        "texturesCaptureTheFlag.cat",
        "texturesConquest.cat",

    ],
    "Honor": [
        "audio_CaptureTheFlag.cat",
        "audio_common.cat",
        "audio_conquest.cat",
        "textures.cat",
        "texturesCaptureTheFlag.cat",
        "texturesconquest.cat",

    ],
    "LittleBigEye": [
        "audio_CaptureTheFlag.cat",
        "audio_common.cat",
        "audio_conquest.cat",
        "textures.cat",
        "texturesCaptureTheFlag.cat",
        "texturesconquest.cat",

    ],
    "MissileCrisis": [
        "audio_CaptureTheFlag.cat",
        "audio_common.cat",
        "audio_conquest.cat",
        "textures.cat",
        "texturesCaptureTheFlag.cat",
        "texturesconquest.cat",

    ],
    "RussianBorder": [
        "audio_CaptureTheFlag.cat",
        "audio_common.cat",
        "audio_conquest.cat",
        "textures.cat",
        "texturesCaptureTheFlag.cat",
        "texturesconquest.cat",

    ],
    "SpecialOp": [
        "audio_CaptureTheFlag.cat",
        "audio_common.cat",
        "audio_conquest.cat",
        "textures.cat",
        "texturesCaptureTheFlag.cat",
        "texturesconquest.cat",

    ],
    "TheBlackGold": [
        "audio_CaptureTheFlag.cat",
        "audio_common.cat",
        "audio_conquest.cat",
        "textures.cat",
        "texturesconquest.cat",

    ],
    "TheNest": [
        "audio_CaptureTheFlag.cat",
        "audio_common.cat",
        "audio_Conquest.cat",
        "textures.cat",
        "texturesCaptureTheFlag.cat",
        "texturesConquest.cat",

    ],
}